version: "3.9"
services:
  api:
    build: .
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5433:5432"
